version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: "serverName=0.0.0.0"
    volumes:
      - '.:/app'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/postgres/datadir:/var/lib/postgresql/data
      - ./config/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
